# Generated by Django 4.1.6 on 2023-02-01 19:37

from django.db import migrations

def add_sample_data(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    SimpleModel = apps.get_model('main_app', 'SimpleModel')
    SimpleModel.objects.create(just_text="Text 1")
    SimpleModel.objects.create(just_text="Text 2")

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_sample_data),
    ]
